version: "3.3"
services:
  prometheus:
    image: localhost/prometheus:latest
    restart: always
    network_mode: host
    volumes:
      - mgmt.prometheus:/prometheus
      - type: bind
        source: ./config/prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: localhost/grafana:latest
    restart: always
    network_mode: host
    volumes:
      - mgmt.grafana:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  mgmt.prometheus:
    external: true
  mgmt.grafana:
    external: true