global:
  scrape_interval: 10m
  scrape_timeout: 40s
scrape_configs:
  - job_name: oniontree
    bearer_token: "{{ mgmt_prometheus_metrics_auth }}"
    proxy_url: socks5://127.0.0.1:9050
    static_configs:
      - targets: ["onions53ehmf4q75.onion"]

  - job_name: vworp
    bearer_token: "{{ mgmt_prometheus_metrics_auth }}"
    proxy_url: socks5://127.0.0.1:9050
    static_configs:
      - targets: ["vworp2mspe566cws.onion"]

  - job_name: hxxpbeam
    bearer_token: "{{ mgmt_prometheus_metrics_auth }}"
    proxy_url: socks5://127.0.0.1:9050
    static_configs:
      - targets: ["qf6ycc37agiwvunc757l4427guhdawqngjqs4bfn3kenwszpjnk53sqd.onion"]
