version: "3.3"
services:
  tor_hs:
    image: localhost/tor-hidden-service:v0.4.3.5
    restart: always
    environment:
      HTTPD_TOR_SERVICE_HOSTS: 80:httpd:8080
      HTTPD_TOR_SERVICE_VERSION: 2
      HXXPBEAM_TOR_SERVICE_HOSTS: 80:hxxpbeam:8080
      HXXPBEAM_TOR_SERVICE_VERSION: 3
      TOR_EXTRA_OPTIONS: |
        DataDirectory /var/lib/tor/hidden_service
        ControlPort 0.0.0.0:9051
        HashedControlPassword 16:AD24C66CB51CFF37600A296F5E2FDF51BA0BBFE19DB4D2786BF5FA7E5D
    networks:
      oniontree.public:
    volumes:
      - oniontree.tor_hs.keys:/var/lib/tor/hidden_service/
    secrets:
      - source: httpd
        target: httpd
      - source: hxxpbeam
        target: hxxpbeam
    depends_on:
      - httpd
      - hxxpbeam

  vanguards_hs:
    image: localhost/vanguards:latest
    restart: always
    environment:
      GLOBAL_CONTROL_IP: tor_hs
      GLOBAL_CONTROL_PORT: 9051
      GLOBAL_CONTROL_PASS: password1
      GLOBAL_ENABLE_VANGUARDS: "True"
      GLOBAL_ENABLE_BANDGUARDS: "True"
      GLOBAL_ENABLE_CBTVERIFY: "False"
      GLOBAL_ENABLE_RENDGUARD: "True"
      GLOBAL_CLOSE_CIRCUITS: "True"
      GLOBAL_ONE_SHOT_VANGUARDS: "False"
      GLOBAL_LOGLEVEL: NOTICE
      VANGUARDS_LAYER1_LIFETIME_DAYS: 0
      VANGUARDS_MAX_LAYER2_LIFETIME_HOURS: 1080
      VANGUARDS_MAX_LAYER3_LIFETIME_HOURS: 48
      VANGUARDS_MIN_LAYER2_LIFETIME_HOURS: 24
      VANGUARDS_MIN_LAYER3_LIFETIME_HOURS: 1
      VANGUARDS_NUM_LAYER1_GUARDS: 2
      VANGUARDS_NUM_LAYER2_GUARDS: 3
      VANGUARDS_NUM_LAYER3_GUARDS: 8
      BANGUARDS_CIRC_MAX_AGE_HOURS: 24
      BANGUARDS_CIRC_MAX_HSDESC_KILOBYTES: 30
      BANGUARDS_CIRC_MAX_MEGABYTES: 0
      BANGUARDS_CIRC_MAX_DISCONNECTED_SECS: 30
      BANGUARDS_CONN_MAX_DISCONNECTED_SECS: 15
      RENDGUARD_REND_USE_MAX_USE_TO_BW_RATIO: 5.0
      RENDGUARD_REND_USE_MAX_CONSENSUS_WEIGHT_CHURN: 1.0
      RENDGUARD_REND_USE_CLOSE_CIRCUITS_ON_OVERUSE: "True"
      RENDGUARD_REND_USE_GLOBAL_START_COUNT: 1000
      RENDGUARD_REND_USE_RELAY_START_COUNT: 100
      RENDGUARD_REND_USE_SCALE_AT_COUNT: 20000
    networks:
      oniontree.public:
    volumes:
      - oniontree.tor_hs.keys:/var/lib/tor/hidden_service/
    depends_on:
      - tor_hs

  httpd:
    image: localhost/httpd:latest
    restart: always
    environment:
      HTTP_LISTEN: 0.0.0.0:8080
      WWW_PATH: /home/user/data/ro/www
      TORSOCKS_TOR_ADDRESS: haproxy
      TORSOCKS_TOR_PORT: 9050
      PROMETHEUS_METRICS_AUTH: "{{ prometheus_metrics_auth }}"
    networks:
      oniontree.public:
      proxypool.public:
    volumes:
      - oniontree.httpd.data.ro:/home/user/data/ro:ro

  hxxpbeam:
    image: localhost/hxxpbeam:latest
    restart: always
    environment:
      HTTP_LISTEN: 0.0.0.0:8080
      ONIONTREE_PATH: /home/user/data/ro/oniontree
      MONITOR_CONNECTIONS_MAX: 64
      MONITOR_PING_INTERVAL: 10m
      MONITOR_PING_TIMEOUT: 50s
      TORSOCKS_TOR_ADDRESS: haproxy
      TORSOCKS_TOR_PORT: 9050
    networks:
      oniontree.public:
      proxypool.public:
    volumes:
      - oniontree.hxxpbeam.data.ro:/home/user/data/ro:ro

  gitsync_www:
    image: localhost/gitsync:latest
    restart: always
    environment:
      REPOSITORY: https://github.com/oniontree-org/oniontree-org.onion
      REPOSITORY_SYNC_INTERVAL: 5m
      OUTPUT_PATH: /home/user/data/rw/www
      PGP_KEYRING: /home/user/data/ro/pgp.txt
      TORSOCKS_TOR_ADDRESS: haproxy
      TORSOCKS_TOR_PORT: 9050
    networks:
      oniontree.public:
      proxypool.public:
    volumes:
      - oniontree.gitsync.data.ro:/home/user/data/ro:ro
      - oniontree.httpd.data.ro:/home/user/data/rw

  gitsync_oniontree:
    image: localhost/gitsync:latest
    restart: always
    environment:
      REPOSITORY: http://rootgit4rghbuenb.onion/onionltd/oniontree.git
      REPOSITORY_SYNC_INTERVAL: 5m
      OUTPUT_PATH: /home/user/data/rw/oniontree
      PGP_KEYRING: /home/user/data/ro/pgp.txt
      TORSOCKS_TOR_ADDRESS: haproxy
      TORSOCKS_TOR_PORT: 9050
    networks:
      oniontree.public:
      proxypool.public:
    volumes:
      - oniontree.gitsync.data.ro:/home/user/data/ro:ro
      - oniontree.hxxpbeam.data.ro:/home/user/data/rw

networks:
  proxypool.public:
    external: true
  oniontree.public:
    driver: bridge

volumes:
  oniontree.tor_hs.keys:
  oniontree.httpd.data.ro:
    external: true
  oniontree.hxxpbeam.data.ro:
    external: true
  oniontree.gitsync.data.ro:
    external: true

secrets:
  httpd:
    file: ./secrets/httpd/private_key
  hxxpbeam:
    file: ./secrets/hxxpbeam/hs_ed25519_secret_key
