---
- hosts: proxypool
  roles:
    - role: common_handlers
      vars:
        stack: proxypool

    - role: docker_update_image
      vars:
        image: "{{ haproxy_image }}"
      tags:
        - haproxy

    - role: docker_update_image
      vars:
        image: "{{ tor_image }}"
      tags:
        - tor

    - role: docker_update_image
      vars:
        image: "{{ vanguards_image }}"
      tags:
        - vanguards
