---
- hosts: oniontree
  gather_facts: no
  tasks:
    - import_role:
        name: common_handlers
      vars:
        stack: oniontree

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ tor_image }}"
      tags:
        - tor

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ vanguards_image }}"
      tags:
        - vanguards

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ httpd_image }}"
      tags:
        - httpd

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ hxxpbeam_image }}"
      tags:
        - hxxpbeam

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ gitsync_image }}"
      tags:
        - gitsync

    - import_role:
        name: swarm_oniontree
      tags:
        - swarm
