---
- hosts: vworp
  gather_facts: no
  tasks:
    - import_role:
        name: common_handlers
      vars:
        stack: vworp

    - import_role:
        name: common_handlers
      vars:
        stack: proxypool

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ tor_image }}"
      tags:
        - tor

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ vanguards_image }}"
      tags:
        - vanguards

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ vworp_image }}"
      tags:
        - vworp

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ gitsync_image }}"
      tags:
        - gitsync

    - import_role:
        name: swarm_proxypool
      tags:
        - proxypool

    - import_role:
        name: swarm_vworp
      tags:
        - swarm
