---
- hosts: proxypool
  tasks:
    - import_role:
        name: docker_update_image
      vars:
        image: "{{ haproxy_image }}"
      notify: Restart stack proxypool
      tags:
        - haproxy

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ tor_image }}"
      notify: Restart stack proxypool
      tags:
        - tor

    - import_role:
        name: docker_update_image
      vars:
        image: "{{ vanguards_image }}"
      notify: Restart stack proxypool
      tags:
        - vanguards

    - import_role:
        name: swarm_vworp
      tags:
        - swarm
